[manager]
layout         = [ 1, 4, 3 ]
sort_by        = "modified"
sort_sensitive = true
sort_reverse   = true
sort_dir_first = true
show_hidden    = true
show_symlink   = true

[preview]
tab_size   = 2
max_width  = 1000
max_height = 1000
cache_dir  = "~/.cache"

[opener]
folder = [
	{ exec = 'open -R "$@"', desc = "Reveal in Finder" },
	{ exec = '$EDITOR "$@"' },
]
archive = [
	{ exec = 'unar "$1"', desc = "Extract here" },
]
text = [
	{ exec = '$EDITOR "$@"', block= true },
]

image = [
	{ exec = 'imv-dir  "$@"',block = true},
  { exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF" },
]


pdf = [

	{exec = 'zathura "$@"',block = true}

]

video = [
	{ exec = 'mpv "$@"',block= true },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
audio = [
	{ exec = 'mpv --no-video "$@"',block=true },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]


fallback = [
	{ exec = 'xdg-open "$@"', desc = "Open" },
	{ exec = 'xdg-open -R "$@"', desc = "Reveal in Finder" },
]

[open]
rules = [
	{ name = "*/", use = "folder" },
  { mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "inode/x-empty", use = "text" },

	{ mime = "application/json", use = "text" },
	{ mime = "*/javascript", use = "text" },

	{ mime = "application/zip", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
	{ mime = "application/x-rar", use = "archive" },
	{ mime = "application/pdf", use = "pdf" },
 	

{ mime = "*", use = "fallback" },
  
]


[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[plugins]
preload = ["~/dotfiles/yazi/ui.lua",
          "~/dotfiles/yazi/status.lua"]


[log]
enabled = false
