[manager]
layout         = [ 1, 4, 3 ]
sort_by        = "modified"
sort_sensitive = true
sort_reverse   = true
sort_dir_first = true
show_hidden    = true
show_symlink   = true

[preview]
tab_size   = 2
max_width  = 1000
max_height = 1000

[opener]


folder = [
	{ run = 'open -R "$@"', desc = "Reveal in Finder" },
	{ run = '$EDITOR "$@"' },
]

archive = [
	{ run = 'unar "$1"', desc = "Extract here" },
]

text = [
	{ run = '$EDITOR "$@"', block= true },
]

image = [
	{ run = 'imv-dir  "$@"',block = true},
  { run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF" },
]


pdf = [

	{run = 'zathura "$@"',block = true}

]

video = [
	{ run = 'mpv "$@"',block= true },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]

audio = [
	{ run = 'mpv --no-video "$@"',block=true },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]


fallback = [
	{ run = 'xdg-open "$@"', desc = "Open" },
	{ run = 'xdg-open -R "$@"', desc = "Reveal in Finder" },
]

[open]
rules = [
	{ name = "*/", use = "folder" },
	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "inode/x-empty", use = "text" },

	{ mime = "application/json", use = "text" },
	{ mime = "*/javascript", use = "text" },

	{ mime = "application/zip", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
	{ mime = "application/x-rar", use = "archive" },
	{ mime = "application/pdf", use = "pdf" },
 	{ mime = "*", use = "fallback" },
  
]


[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5



[plugins]
preload = ["~/dotfiles/yazi/ui.lua",
          "~/dotfiles/yazi/status.lua"]




[[plugin.prepend_previewers]]
mime = "audio/*"
run = "exifaudio"


[[manager.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = [ "f","g" ]
run  = "plugin fg"
desc = "find file by content"


[[manager.prepend_keymap]]
on   = [ "f","f" ]
run  = "plugin fg --args='fzf'"
desc = "find file by file name"

[log]
enabled = true
